---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

This is a line from RStudio

## step 12.2
-Ewan's notes: copying the URL was pretty simple when following the directions

## step 12.3
-Ewan's notes: I had no issues creating a new project and the directions were easy to follow

## step 12.4
-Ewan's notes: I had no problems making and saving a change

## step 12.5
-Ewan's notes: It was a little hard to see where the push button was at first, but I had no issue after that
